language: node_js
node_js:
  - "7"
before_install:
  - 'npm install -g npm@5.5.1'
install: npm i
script: npm run build && npm test
cache:
  directories:
    - "node_modules"
notifications:
  email: false
